services:
  # ========================================================
  # MLflow
  # ========================================================

  mlflow-server:
    build:
      context: .
      dockerfile: mlflow.Dockerfile

    container_name: mlflow-server

    ports:
      - "5000:5000"

    volumes:
      - ./mlflow-data:/mlflow

    networks:
      - mlops-network

  # ========================================================
  # FastAPI
  # ========================================================

  salary-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: salary-api

    ports:
      - "8000:8000"

    environment:
      MLFLOW_TRACKING_URI: http://mlflow-server:5000
      SALARY_REGISTERED_MODEL_NAME: salary_prediction_model
      SALARY_MODEL_ALIAS: production

    depends_on:
      - mlflow-server

    networks:
      - mlops-network

  # ========================================================
  # Frontend
  # ========================================================

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: salary-frontend

    ports:
      - "3000:80"

    depends_on:
      - salary-api

    networks:
      - mlops-network

# ==========================================================
# Docker network
# ==========================================================

networks:
  mlops-network:
    driver: bridge
